name: Origin Repository Workflow

on:
  push:
    branches:
      - main

jobs:
  trigger-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger workflow in another repository
        id: trigger
        uses: amandastecz/pipeline-trigger@v1.1
        with:
          pat-token: ${{ secrets.PAT_TOKEN }}
          owner: Prakhar10747884
          repo: usecase7_target
      

      - name: Log response
        run: echo "Response:${{ steps.trigger.outputs.response }}"
